{"uid":"d25ebf36a2aa72cf","name":"test_api[GET /users/{user_id}]","fullName":"tests.test_schemathesis_dynamic#test_api","historyId":"dcd2f99f5c08f81fe34236b8aea32418","time":{"start":1761370496066,"stop":1761370496101,"duration":35},"status":"broken","statusMessage":"schemathesis.core.failures.FailureGroup: Schemathesis found 1 distinct failure\n\n- Undocumented HTTP status code\n\n    Received: 404\n    Documented: 200, 422\n\n[404] Not Found:\n\n    `{\"detail\":\"User not found\"}`\n\nReproduce with: \n\n    curl -X GET http://localhost:8000/users/0\n\n (1 sub-exception)","statusTrace":"+ Exception Group Traceback (most recent call last):\n  |   File \"/opt/hostedtoolcache/Python/3.11.13/x64/lib/python3.11/site-packages/_pytest/runner.py\", line 341, in from_call\n  |     result: Optional[TResult] = func()\n  |                                 ^^^^^^\n  |   File \"/opt/hostedtoolcache/Python/3.11.13/x64/lib/python3.11/site-packages/_pytest/runner.py\", line 241, in <lambda>\n  |     lambda: runtest_hook(item=item, **kwds), when=when, reraise=reraise\n  |             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  |   File \"/opt/hostedtoolcache/Python/3.11.13/x64/lib/python3.11/site-packages/pluggy/_hooks.py\", line 512, in __call__\n  |     return self._hookexec(self.name, self._hookimpls.copy(), kwargs, firstresult)\n  |            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  |   File \"/opt/hostedtoolcache/Python/3.11.13/x64/lib/python3.11/site-packages/pluggy/_manager.py\", line 120, in _hookexec\n  |     return self._inner_hookexec(hook_name, methods, kwargs, firstresult)\n  |            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  |   File \"/opt/hostedtoolcache/Python/3.11.13/x64/lib/python3.11/site-packages/pluggy/_callers.py\", line 167, in _multicall\n  |     raise exception\n  |   File \"/opt/hostedtoolcache/Python/3.11.13/x64/lib/python3.11/site-packages/pluggy/_callers.py\", line 139, in _multicall\n  |     teardown.throw(exception)\n  |   File \"/opt/hostedtoolcache/Python/3.11.13/x64/lib/python3.11/site-packages/_pytest/threadexception.py\", line 87, in pytest_runtest_call\n  |     yield from thread_exception_runtest_hook()\n  |   File \"/opt/hostedtoolcache/Python/3.11.13/x64/lib/python3.11/site-packages/_pytest/threadexception.py\", line 63, in thread_exception_runtest_hook\n  |     yield\n  |   File \"/opt/hostedtoolcache/Python/3.11.13/x64/lib/python3.11/site-packages/pluggy/_callers.py\", line 139, in _multicall\n  |     teardown.throw(exception)\n  |   File \"/opt/hostedtoolcache/Python/3.11.13/x64/lib/python3.11/site-packages/_pytest/unraisableexception.py\", line 90, in pytest_runtest_call\n  |     yield from unraisable_exception_runtest_hook()\n  |   File \"/opt/hostedtoolcache/Python/3.11.13/x64/lib/python3.11/site-packages/_pytest/unraisableexception.py\", line 65, in unraisable_exception_runtest_hook\n  |     yield\n  |   File \"/opt/hostedtoolcache/Python/3.11.13/x64/lib/python3.11/site-packages/pluggy/_callers.py\", line 139, in _multicall\n  |     teardown.throw(exception)\n  |   File \"/opt/hostedtoolcache/Python/3.11.13/x64/lib/python3.11/site-packages/_pytest/logging.py\", line 850, in pytest_runtest_call\n  |     yield from self._runtest_for(item, \"call\")\n  |   File \"/opt/hostedtoolcache/Python/3.11.13/x64/lib/python3.11/site-packages/_pytest/logging.py\", line 833, in _runtest_for\n  |     yield\n  |   File \"/opt/hostedtoolcache/Python/3.11.13/x64/lib/python3.11/site-packages/pluggy/_callers.py\", line 139, in _multicall\n  |     teardown.throw(exception)\n  |   File \"/opt/hostedtoolcache/Python/3.11.13/x64/lib/python3.11/site-packages/pluggy/_callers.py\", line 53, in run_old_style_hookwrapper\n  |     return result.get_result()\n  |            ^^^^^^^^^^^^^^^^^^^\n  |   File \"/opt/hostedtoolcache/Python/3.11.13/x64/lib/python3.11/site-packages/pluggy/_result.py\", line 103, in get_result\n  |     raise exc.with_traceback(tb)\n  |   File \"/opt/hostedtoolcache/Python/3.11.13/x64/lib/python3.11/site-packages/pluggy/_callers.py\", line 38, in run_old_style_hookwrapper\n  |     res = yield\n  |           ^^^^^\n  |   File \"/opt/hostedtoolcache/Python/3.11.13/x64/lib/python3.11/site-packages/pluggy/_callers.py\", line 139, in _multicall\n  |     teardown.throw(exception)\n  |   File \"/opt/hostedtoolcache/Python/3.11.13/x64/lib/python3.11/site-packages/_pytest/capture.py\", line 878, in pytest_runtest_call\n  |     return (yield)\n  |             ^^^^^\n  |   File \"/opt/hostedtoolcache/Python/3.11.13/x64/lib/python3.11/site-packages/pluggy/_callers.py\", line 139, in _multicall\n  |     teardown.throw(exception)\n  |   File \"/opt/hostedtoolcache/Python/3.11.13/x64/lib/python3.11/site-packages/pluggy/_callers.py\", line 53, in run_old_style_hookwrapper\n  |     return result.get_result()\n  |            ^^^^^^^^^^^^^^^^^^^\n  |   File \"/opt/hostedtoolcache/Python/3.11.13/x64/lib/python3.11/site-packages/pluggy/_result.py\", line 103, in get_result\n  |     raise exc.with_traceback(tb)\n  |   File \"/opt/hostedtoolcache/Python/3.11.13/x64/lib/python3.11/site-packages/pluggy/_callers.py\", line 38, in run_old_style_hookwrapper\n  |     res = yield\n  |           ^^^^^\n  |   File \"/opt/hostedtoolcache/Python/3.11.13/x64/lib/python3.11/site-packages/pluggy/_callers.py\", line 139, in _multicall\n  |     teardown.throw(exception)\n  |   File \"/opt/hostedtoolcache/Python/3.11.13/x64/lib/python3.11/site-packages/_pytest/skipping.py\", line 257, in pytest_runtest_call\n  |     return (yield)\n  |             ^^^^^\n  |   File \"/opt/hostedtoolcache/Python/3.11.13/x64/lib/python3.11/site-packages/pluggy/_callers.py\", line 121, in _multicall\n  |     res = hook_impl.function(*args)\n  |           ^^^^^^^^^^^^^^^^^^^^^^^^^\n  |   File \"/opt/hostedtoolcache/Python/3.11.13/x64/lib/python3.11/site-packages/_pytest/runner.py\", line 173, in pytest_runtest_call\n  |     item.runtest()\n  |   File \"/opt/hostedtoolcache/Python/3.11.13/x64/lib/python3.11/site-packages/_pytest/python.py\", line 1632, in runtest\n  |     self.ihook.pytest_pyfunc_call(pyfuncitem=self)\n  |   File \"/opt/hostedtoolcache/Python/3.11.13/x64/lib/python3.11/site-packages/pluggy/_hooks.py\", line 512, in __call__\n  |     return self._hookexec(self.name, self._hookimpls.copy(), kwargs, firstresult)\n  |            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  |   File \"/opt/hostedtoolcache/Python/3.11.13/x64/lib/python3.11/site-packages/pluggy/_manager.py\", line 120, in _hookexec\n  |     return self._inner_hookexec(hook_name, methods, kwargs, firstresult)\n  |            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  |   File \"/opt/hostedtoolcache/Python/3.11.13/x64/lib/python3.11/site-packages/pluggy/_callers.py\", line 167, in _multicall\n  |     raise exception\n  |   File \"/opt/hostedtoolcache/Python/3.11.13/x64/lib/python3.11/site-packages/pluggy/_callers.py\", line 139, in _multicall\n  |     teardown.throw(exception)\n  |   File \"/opt/hostedtoolcache/Python/3.11.13/x64/lib/python3.11/site-packages/schemathesis/pytest/plugin.py\", line 307, in pytest_pyfunc_call\n  |     yield\n  |   File \"/opt/hostedtoolcache/Python/3.11.13/x64/lib/python3.11/site-packages/pluggy/_callers.py\", line 121, in _multicall\n  |     res = hook_impl.function(*args)\n  |           ^^^^^^^^^^^^^^^^^^^^^^^^^\n  |   File \"/opt/hostedtoolcache/Python/3.11.13/x64/lib/python3.11/site-packages/_pytest/python.py\", line 162, in pytest_pyfunc_call\n  |     result = testfunction(**testargs)\n  |              ^^^^^^^^^^^^^^^^^^^^^^^^\n  |   File \"/opt/hostedtoolcache/Python/3.11.13/x64/lib/python3.11/site-packages/schemathesis/generation/hypothesis/builder.py\", line 222, in test_api\n  |     def test_wrapper(*args: Any, **kwargs: Any) -> Any:\n  |                ^^^\n  |   File \"/opt/hostedtoolcache/Python/3.11.13/x64/lib/python3.11/site-packages/hypothesis/core.py\", line 2052, in wrapped_test\n  |     _raise_to_user(errors, state.settings, [], \" in explicit examples\")\n  |   File \"/opt/hostedtoolcache/Python/3.11.13/x64/lib/python3.11/site-packages/hypothesis/core.py\", line 1603, in _raise_to_user\n  |     raise the_error_hypothesis_found\n  |   File \"/opt/hostedtoolcache/Python/3.11.13/x64/lib/python3.11/site-packages/schemathesis/generation/hypothesis/builder.py\", line 224, in test_wrapper\n  |     return test_function(*args, **kwargs)\n  |            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  |   File \"/home/runner/work/custom-api-testing-showcase/custom-api-testing-showcase/tests/test_schemathesis_dynamic.py\", line 33, in test_api\n  |     case.call_and_validate()\n  |   File \"/opt/hostedtoolcache/Python/3.11.13/x64/lib/python3.11/site-packages/schemathesis/generation/case.py\", line 328, in call_and_validate\n  |     self.validate_response(\n  |   File \"/opt/hostedtoolcache/Python/3.11.13/x64/lib/python3.11/site-packages/schemathesis/generation/case.py\", line 302, in validate_response\n  |     raise FailureGroup(_failures, message) from None\n  | schemathesis.core.failures.FailureGroup: Schemathesis found 1 distinct failure\n  | \n  | - Undocumented HTTP status code\n  | \n  |     Received: 404\n  |     Documented: 200, 422\n  | \n  | [404] Not Found:\n  | \n  |     `{\"detail\":\"User not found\"}`\n  | \n  | Reproduce with: \n  | \n  |     curl -X GET http://localhost:8000/users/0\n  | \n  |  (1 sub-exception)\n  +-+---------------- 1 ----------------\n    | schemathesis.openapi.checks.UndefinedStatusCode: Undocumented HTTP status code\n    | \n    | Received: 404\n    | Documented: 200, 422\n    +------------------------------------","flaky":false,"newFailed":false,"newBroken":false,"newPassed":false,"retriesCount":0,"retriesStatusChange":false,"beforeStages":[],"afterStages":[],"labels":[{"name":"epic","value":"API Testing Showcase"},{"name":"suite","value":"API"},{"name":"parentSuite","value":"API"},{"name":"subSuite","value":"API"},{"name":"tag","value":"hypothesis"},{"name":"host","value":"runnervmwhb2z"},{"name":"thread","value":"2570-MainThread"},{"name":"framework","value":"pytest"},{"name":"language","value":"cpython3"},{"name":"package","value":"tests.test_schemathesis_dynamic"},{"name":"resultFormat","value":"allure2"}],"parameters":[],"links":[],"hidden":true,"retry":true,"extra":{"categories":[],"tags":["hypothesis"]},"source":"d25ebf36a2aa72cf.json","parameterValues":[]}